#ifndef mdk_LinearAlgebra_Function_SparseMatrix_h
#define mdk_LinearAlgebra_Function_SparseMatrix_h

#include "mdkLinearAlgebra_Function_SparseMatrix_Part_0.h"
#include "mdkLinearAlgebra_Function_SparseMatrix_Part_1.h"
#include "mdkLinearAlgebra_Function_SparseMatrix_Part_2.h"

#endif
