#ifndef __mdkLinearAlgebra_Function_DenseMatrix_h
#define __mdkLinearAlgebra_Function_DenseMatrix_h

#include "mdkLinearAlgebra_Function_DenseMatrix_Part_0.h"
#include "mdkLinearAlgebra_Function_DenseMatrix_Part_1.h"
#include "mdkLinearAlgebra_Function_DenseMatrix_Part_2.h"
#include "mdkLinearAlgebra_Function_DenseMatrix_Part_3.h"

#endif
